# Generated by Django 5.0.1 on 2024-02-01 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=7)),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('home_team_goals', models.IntegerField()),
                ('away_team_goals', models.IntegerField()),
                ('total_goals', models.IntegerField()),
                ('winner', models.CharField(max_length=100)),
                ('loser', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='MonModele',
        ),
    ]
